# Generated by Django 5.2.1 on 2025-05-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Базовая цена для стандартного размера', max_digits=6, verbose_name='Базовая цена'),
        ),
    ]
