# Generated by Django 5.2.1 on 2025-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_order_pizzas_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
