# Generated by Django 5.2.1 on 2025-05-25 14:17

import django.core.validators
import pizza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Должно быть 18+ лет', null=True, validators=[pizza.models.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Должно быть 18+ лет', null=True, validators=[pizza.models.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (29) XXX-XX-XX', max_length=19, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\((?:29|33|44|25)\\) [0-9]{3}-[0-9]{2}-[0-9]{2}$')]),
        ),
    ]
