# Generated by Django 5.2.1 on 2025-05-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='promos', to='pizza.customer'),
        ),
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
