# Generated by Django 5.2.1 on 2025-09-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_companyinfo_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
