# Generated by Django 5.2.1 on 2025-09-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_banner_link_partnercompany_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
    ]
