# Generated by Django 5.2.1 on 2025-09-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
