# Generated by Django 5.2.1 on 2025-09-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_promo_customers_promo_description_promo_title'),
        ('pizza', '0003_banner_partnercompany_cart_cartitem'),
    ]

    operations = [
    ]
